[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = stm32cube

; Flag para o upload simples funcionar com o clone
upload_flags = -c set CPUTAPID 0x2ba01477

; Configuração completa do servidor de debug
debug_server =
  C:\Users\Lucas\.platformio\packages\tool-openocd\bin\openocd.exe
  -s C:\Users\Lucas\.platformio\packages\tool-openocd\scripts
  -f interface/stlink.cfg
  -c "transport select hla_swd"
  -c "set CPUTAPID 0x2ba01477"
  -f target/stm32f1x.cfg
  -c "reset_config none"